[package]
name = "prediction-market-event"
version = "0.1.0"
edition = "2021"

[dependencies]
nostr-sdk = "0.34.0"
rand = "0.8.5"
serde = { version = "1.0.209", features = [ "derive" ] }
serde_json = "1.0.127"
sha2 = "0.10.8"
